### PR TITLE
deps: remove black

### PR DESCRIPTION
**Pull request by steveoh**
closes #85

### CODE REVIEW

**Comment by stdavis** [comment]
Was there not any formatting changes to the files?

**Comment by jacobdadams** [comment]
My understanding is that black is packaged with the VSCode extension and linting is handled by ruff, so we don't need to install it as a dep. Do I have that right, @steveoh?

**Comment by steveoh** [comment]
Ruff should provide the same results as black. So removing it shouldn't change the files. I did not run the formatting code since removing black removes the need to do any dbot updates.

**Comment by steveoh** [comment]
> My understanding is that black is packaged with the VSCode extension and linting is handled by ruff, so we don't need to install it as a dep. Do I have that right, @steveoh?

Ruff is a drop in replacement for black. Black isn't required anywhere any longer. We should be using the ruff vscode extension and using ruff for linting.

**Review by stdavis — APPROVED** [review]

**Pull request merged**
